language: c
install: echo "install"
script: make

compiler:
  - clang
  - gcc
  - gcc-4.9
  - gcc-7

os:
  - osx
  - linux

before_install:
  - eval "${MATRIX_EVAL}"

git:
  depth: 10
  submodules: true

